<h2>All Courses</h2>
<ul>
    @foreach($courses as $course)
    <li>
        <strong>{{ $course->title }}</strong><br>
        {{ $course->description }}
    </li>
    @endforeach
</ul>

<p><strong>Generated by:</strong> {{ Auth::user()->name }} ({{ Auth::user()->role }})</p>
<p><strong>Date:</strong> {{ now()->format('F d, Y') }}</p>