<h2>Course Details</h2>
<p><strong>Title:</strong> {{ $course->title }}</p>
<p><strong>Description:</strong> {{ $course->description }}</p>
<p><strong>Generated by:</strong> {{ Auth::user()->name }} ({{ Auth::user()->role }})</p>
<p><strong>Date:</strong> {{ now()->format('F d, Y') }}</p>