<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Course Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 14px;
        }

        .section {
            margin-bottom: 1rem;
        }

        h1,
        h2 {
            text-align: center;
        }

        .field {
            margin-bottom: 0.5rem;
        }

        .label {
            font-weight: bold;
        }
    </style>
</head>

<body>
    <h1>Course Report</h1>

    <div class="section">
        <div class="field">
            <span class="label">Title:</span> {{ $course->title }}
        </div>
        <div class="field">
            <span class="label">Created At:</span> {{ $course->created_at->format('Y-m-d') }}
        </div>
    </div>

    <p style="text-align: center;">Generated by LMS System</p>
</body>

</html>