<!DOCTYPE html>
<html>

<head>
    <title>Enrollment Record</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            box-sizing: border-box;
        }

        .record-container {
            background: white;
            border-radius: 12px;
            padding: 40px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            position: relative;
            overflow: hidden;
        }

        .record-container::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 6px;
            background: linear-gradient(90deg, #667eea, #764ba2);
        }

        h2 {
            color: #2d3748;
            font-size: 2.5em;
            margin-bottom: 30px;
            text-align: center;
            font-weight: 300;
            letter-spacing: -0.5px;
        }

        .info-grid {
            display: grid;
            gap: 25px;
            margin-bottom: 30px;
        }

        .info-item {
            padding: 20px;
            background: #f8fafc;
            border-radius: 8px;
            border-left: 4px solid #667eea;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }

        .info-item:hover {
            transform: translateX(5px);
            box-shadow: 0 5px 15px rgba(102, 126, 234, 0.1);
        }

        .info-label {
            font-weight: 600;
            color: #4a5568;
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 8px;
        }

        .info-value {
            color: #2d3748;
            font-size: 1.1em;
            font-weight: 500;
        }

        .divider {
            height: 2px;
            background: linear-gradient(90deg, transparent, #e2e8f0, transparent);
            margin: 30px 0;
        }

        .footer {
            text-align: center;
            color: #718096;
            font-size: 0.9em;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
        }

        .accent {
            color: #667eea;
            font-weight: 600;
        }
    </style>
</head>

<body>
    <div class="record-container">
        <h2>Enrollment Record</h2>

        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">Student Name</div>
                <div class="info-value">{{ $enrollment->user->name }}</div>
            </div>

            <div class="info-item">
                <div class="info-label">Subject</div>
                <div class="info-value">{{ $enrollment->subject->name }}</div>
            </div>

            <div class="info-item">
                <div class="info-label">Enrollment Date</div>
                <div class="info-value">{{ \Carbon\Carbon::parse($enrollment->enrolled_at)->format('F d, Y') }}</div>
            </div>
        </div>

        <div class="divider"></div>

        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">Generated By</div>
                <div class="info-value">{{ Auth::user()->name }} <span class="accent">({{ Auth::user()->role }})</span></div>
            </div>

            <div class="info-item">
                <div class="info-label">Generated On</div>
                <div class="info-value">{{ now()->format('F d, Y') }}</div>
            </div>
        </div>

        <div class="footer">
            <p>This is an official enrollment record generated by the system.</p>
        </div>
    </div>
</body>

</html>