<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>My Enrollments Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
        }

        .date {
            font-size: 14px;
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">My All Enrollments Report</div>
        <div class="date">Generated on: {{ now()->format('F j, Y') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Subject</th>
                <th>Course</th>
                <th>Enrollment Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($enrollments as $enrollment)
            <tr>
                <td>{{ $enrollment->subject->name }}</td>
                <td>{{ $enrollment->subject->course->title ?? 'N/A' }}</td>
                <td>{{ $enrollment->enrolled_at->format('M d, Y') }}</td>
                <td>Active</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Enrollments: {{ $enrollments->count() }}</p>
        <p>Generated by: {{ Auth::user()->name }}</p>
    </div>
</body>

</html>