<h2>Subject Details</h2>
<p><strong>Name:</strong> {{ $subject->name }}</p>
<p><strong>Course:</strong> {{ $subject->course->title }}</p>
<p><strong>Generated by:</strong> {{ Auth::user()->name }} ({{ Auth::user()->role }})</p>
<p><strong>Date:</strong> {{ now()->format('F d, Y') }}</p>